---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-exporter
  namespace: memcached
spec:
  selector:
    matchLabels:
      app: memcached-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached-exporter
      annotations:
        prometheus.io/port: "9150"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: memcached-exporter
        image: quay.io/prometheus/memcached-exporter:latest
        ports:
          - containerPort: 9150
        command: ["/bin/memcached_exporter"]
        args: ["--memcached.address","memcached:11211"]
        resources:
          limits:
            memory: "256Mi"
            cpu: "256m"