apiVersion: v1
kind: SetupGuide
app: postgreSQL
version: 1.0.0
appVersion:
- "12"
descriptionFile: INSTALL.md
configurations:
- name: postgresql-standalone-db.yaml
  file: include/postgresql-standalone-db.yaml
- name: postgresql-standalone-exporter.yaml
  file: include/postgresql-standalone-exporter.yaml
- name: postgresql-auth-deploy.yaml
  file: include/postgresql-auth-deploy.yaml
