apiVersion: v1
kind: SetupGuide
app: memcached
version: 1.0.0
appVersion:
- '1.6'
descriptionFile: INSTALL.md
configurations:
- name: memcached-deploy.yaml
  file: include/memcached-exporter-deploy.yaml
