apiVersion: v1
kind: SetupGuide
app: php-fpm
version: 1.0.0
appVersion:
- '7.2'
configurations:
- name: deployment.yaml
  file: include/deployment.yaml
- name: sysdig-agent.yaml
  file: include/sysdig-agent.yaml
descriptionFile: INSTALL.md
