apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-sysdig-k8s-rules
  namespace: cattle-prometheus
  labels:
    app: exporter-kubernetes
    source: rancher-monitoring
spec:
  groups:
  - name: "Sysdig.k8s.general.rules"
    rules:
    - expr: up{job=~"expose-kubelets-metrics|kubernetes|controller-manager|kube-controller-manager|kube-scheduler|coredns-monitoring"}
      record: "up:kubernetes"
      labels:
        sysdig: "true"
    - expr: |
        process_resident_memory_bytes{job=~"expose-kubelets-metrics|kubernetes|controller-manager|kube-controller-manager|kube-scheduler|coredns-monitoring"}
      record: "process_resident_memory_bytes:kubernetes"
      labels:
        sysdig: "true"
    - expr: |
        process_cpu_seconds_total{job=~"expose-kubelets-metrics|kubernetes|controller-manager|kube-controller-manager|kube-scheduler|coredns-monitoring"}
      record: "process_cpu_seconds_total:kubernetes"
      labels:
        sysdig: "true"
    - expr: |
        go_goroutines{job=~"expose-kubelets-metrics|kubernetes|controller-manager|kube-controller-manager|kube-scheduler|coredns-monitoring"}
      record: "go_goroutines:kubernetes"
      labels:
        sysdig: "true"

  - name: "Sysdig.k8s.kubelet.rules"
    rules:
    - expr: kubelet_running_pod_count{job="expose-kubelets-metrics"}
      record: "kubelet_running_pod_count:kubelet"
      labels:
        sysdig: "true"
    - expr: kubelet_running_container_count{job="expose-kubelets-metrics"}
      record: "kubelet_running_container_count:kubelet"
      labels:
        sysdig: "true"
    - expr: volume_manager_total_volumes{job="expose-kubelets-metrics"}
      record: "volume_manager_total_volumes:kubelet"
      labels:
        sysdig: "true"
    - expr: volume_manager_total_volumes{job="expose-kubelets-metrics",state="desired_state_of_world"}
      record: "volume_manager_total_volumes:desired:kubelet"
      labels:
        sysdig: "true"
    - expr: kubelet_node_config_error{job="expose-kubelets-metrics"}
      record: "kubelet_node_config_error:kubelet"
      labels:
        sysdig: "true"
    - expr: kubelet_runtime_operations_total{job="expose-kubelets-metrics"}
      record: "kubelet_runtime_operations_total:kubelet"
      labels:
        sysdig: "true"
    - expr: kubelet_runtime_operations_errors_total{job="expose-kubelets-metrics"}
      record: "kubelet_runtime_operations_errors_total:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{job="expose-kubelets-metrics"}[5m])) by (instance, operation_type, le))
      record: "operation_duration_seconds:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        kubelet_pod_start_duration_seconds_count{job="expose-kubelets-metrics"}
      record: "kubelet_pod_start_duration_seconds_count:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        kubelet_pod_worker_duration_seconds_count{job="expose-kubelets-metrics"}
      record: "kubelet_pod_worker_duration_seconds_count:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        histogram_quantile(0.99, sum(rate(kubelet_pod_start_duration_seconds_bucket{job="expose-kubelets-metrics"}[5m])) by (instance, le))
      record: "pod_start_duration_seconds:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        histogram_quantile(0.99, sum(rate(kubelet_pod_worker_duration_seconds_bucket{job="expose-kubelets-metrics"}[5m])) by (instance, le))
      record: "pod_worker_duration_seconds:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        storage_operation_duration_seconds_count{job="expose-kubelets-metrics"}
      record: "storage_operation_duration_seconds_count:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        storage_operation_errors_total{job="expose-kubelets-metrics"}
      record: "storage_operation_errors_total:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        histogram_quantile(0.99, sum(rate(storage_operation_duration_seconds_bucket{job="expose-kubelets-metrics"}[5m])) by (instance, operation_name, volume_plugin, le))
      record: "storage_operation_duration_seconds:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        kubelet_cgroup_manager_duration_seconds_count{job="expose-kubelets-metrics"}
      record: "kubelet_cgroup_manager_duration_seconds_count:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        histogram_quantile(0.99, sum(rate(kubelet_cgroup_manager_duration_seconds_bucket{job="expose-kubelets-metrics"}[5m])) by (instance, operation_type, le))
      record: "cgroup_manager_duration_seconds:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        kubelet_pleg_relist_duration_seconds_count{job="expose-kubelets-metrics"}
      record: "kubelet_pleg_relist_duration_seconds_count:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_interval_seconds_bucket{job="expose-kubelets-metrics"}[5m])) by (instance, le))
      record: "pleg_relist_interval_seconds:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_duration_seconds_bucket{job="expose-kubelets-metrics"}[5m])) by (instance, le))
      record: "pleg_relist_duration_seconds:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        rest_client_requests_total{job="expose-kubelets-metrics"}
      record: "rest_client_requests_total_code:kubelet"
      labels:
        sysdig: "true"
    - expr: |
        histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job="expose-kubelets-metrics"}[5m])) by (instance, verb, url, le))
      record: "request_duration_seconds:kubelet"
      labels:
        sysdig: "true"

  - name: "Sysdig.k8s.scheduler.rules"
    rules:
    - expr: up{job="kube-scheduler"}
      record: "up:kube_scheduler"
      labels:
        sysdig: "true"
    - expr: scheduler_e2e_scheduling_duration_seconds_count{job="kube-scheduler"}
      record: "scheduler_e2e_scheduling_duration_seconds_count:kube_scheduler"
      labels:
        sysdig: "true"
    - expr: scheduler_binding_duration_seconds_count{job="kube-scheduler"}
      record: "scheduler_binding_duration_seconds_count:kube_scheduler"
      labels:
        sysdig: "true"
    - expr: scheduler_scheduling_algorithm_duration_seconds_count{job="kube-scheduler"}
      record: "scheduler_scheduling_algorithm_duration_seconds_count:kube_scheduler"
      labels:
        sysdig: "true"
    - expr: scheduler_volume_scheduling_duration_seconds_count{job="kube-scheduler"}
      record: "scheduler_volume_scheduling_duration_seconds_count:kube_scheduler"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(scheduler_e2e_scheduling_duration_seconds_bucket{job="kube-scheduler"}[5m])) by (instance, le))
      record: "scheduler_volume_scheduling_duration_seconds_count:kube_scheduler"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(scheduler_binding_duration_seconds_bucket{job="kube-scheduler"}[5m])) by (instance, le))
      record: "scheduler_binding_duration_seconds_bucket:kube_scheduler"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(scheduler_scheduling_algorithm_duration_seconds_bucket{job="kube-scheduler"}[5m])) by (instance, le))
      record: "scheduler_scheduling_algorithm_duration_seconds_bucket:kube_scheduler"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(scheduler_volume_scheduling_duration_seconds_bucket{job="kube-scheduler"}[5m])) by (instance, le))
      record: "scheduler_volume_scheduling_duration_seconds_bucket:kube_scheduler"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job="kube-scheduler"}[5m])) by (verb, url, le))
      record: "rest_client_request_latency_seconds_bucket:kube_scheduler"
      labels:
        sysdig: "true"
    - expr: rest_client_requests_total{job="kube-scheduler"}
      record: "rest_client_requests_total:kube_scheduler"
      labels:
        sysdig: "true"
  
  - name: "Sysdig.k8s.api.rules"
    rules:
    - expr: apiserver_request_total{job="kubernetes"}
      record: "apiserver_request_total:kubernetes_apiservers"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job="kubernetes"}[5m])) by (verb, le))
      record: "apiserver_request_duration_seconds_bucket:kubernetes_apiservers"
      labels:
        sysdig: "true"
    - expr: workqueue_adds_total{job="kubernetes"}
      record: "workqueue_adds_total:kubernetes_apiservers"
      labels:
        sysdig: "true"
    - expr: workqueue_depth{job="kubernetes"}
      record: "workqueue_depth:kubernetes_apiservers"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job="kubernetes"}[5m])) by (instance, name, le))
      record: "workqueue_queue_duration_seconds_bucket:kubernetes_apiservers"
      labels:
        sysdig: "true"
    - expr: etcd_helper_cache_entry_total{job="kubernetes"}
      record: "etcd_helper_cache_entry_total:kubernetes_apiservers"
      labels:
        sysdig: "true"
    - expr: etcd_helper_cache_hit_total{job="kubernetes"}
      record: "etcd_helper_cache_hit_total:kubernetes_apiservers"
      labels:
        sysdig: "true"
    - expr: etcd_helper_cache_miss_total{job="kubernetes"}
      record: "etcd_helper_cache_miss_total:kubernetes_apiservers"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99,sum(rate(etcd_request_cache_get_duration_seconds_bucket{job="kubernetes"}[5m])) by (instance, le))
      record: "etcd_request_cache_get_duration_seconds_bucket:kubernetes_apiservers"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99,sum(rate(etcd_request_cache_add_duration_seconds_bucket{job="kubernetes"}[5m])) by (instance, le))
      record: "etcd_request_cache_add_duration_seconds_bucket:kubernetes_apiservers"
      labels:
        sysdig: "true"

  - name: "Sysdig.k8s.controller_manager.rules"
    rules:
    - expr: up{job=~"kube-controller-manager|controller-manager"}
      record: "up:controllermanager"
      labels:
        sysdig: "true"
    - expr: workqueue_adds_total{job=~"kube-controller-manager|controller-manager"}
      record: "workqueue_adds_total:kubernetes_control_manager"
      labels:
        sysdig: "true"
    - expr: workqueue_depth{job=~"kube-controller-manager|controller-manager"}
      record: "workqueue_depth:kubernetes_control_manager"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=~"kube-controller-manager"}[5m])) by (instance, name, le))
      record: "workqueue_queue_duration_seconds_bucket:kubernetes_control_manager"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=~"kubernetes", verb="POST"}[5m])) by (verb, url, le))
      record: "rest_client_request_latency_seconds_bucket:kubernetes_control_manager:post"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=~"kubernetes", verb="GET"}[5m])) by (verb, url, le))
      record: "rest_client_request_latency_seconds_bucket:kubernetes_control_manager:get"
      labels:
        sysdig: "true"
    - expr: rest_client_requests_total{job=~"kube-controller-manager|controller-manager"}
      record: "rest_client_requests_total:kubernetes_control_manager"
      labels:
        sysdig: "true"
  
  - name: "Sysdig.k8s.kube_proxy.rules"
    rules:
    - expr: up{job="kube-proxy"}
      record: "up:kube_proxy"
      labels:
        sysdig: "true"
    - expr : kubeproxy_sync_proxy_rules_duration_seconds_count{job="kube-proxy"}
      record: "kubeproxy_sync_proxy_rules_duration_seconds_count:kube_proxy"
      labels:
        sysdig: "true"
    - expr : histogram_quantile(0.99,rate(kubeproxy_sync_proxy_rules_duration_seconds_bucket{job="kube-proxy"}[5m]))
      record: "kubeproxy_sync_proxy_rules_duration_seconds_bucket:kube_proxy"
      labels:
        sysdig: "true"
    - expr : kubeproxy_network_programming_duration_seconds_count{job="kube-proxy"}
      record: "kubeproxy_network_programming_duration_seconds_count:kube_proxy"
      labels:
        sysdig: "true"
    - expr : histogram_quantile(0.99, sum(rate(kubeproxy_network_programming_duration_seconds_bucket{job="kube-proxy"}[5m])) by (instance, le))
      record: "kubeproxy_network_programming_duration_seconds_bucket:kube_proxy"
      labels:
        sysdig: "true"
    - expr: rest_client_requests_total{job="kube-proxy"}
      record: "rest_client_requests_total:kube_proxy"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job="kube-proxy",verb="POST"}[5m])) by (verb, url, le))
      record: "rest_client_request_latency_seconds_bucket:post:kube_proxy"
      labels:
        sysdig: "true"
    - expr: histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job="kube-proxy",verb="GET"}[5m])) by (verb, url, le))
      record: "rest_client_request_latency_seconds_bucket:get:kube_proxy"
      labels:
        sysdig: "true"
    - expr: |
        process_resident_memory_bytes{job="kube-proxy"}
      record: "process_resident_memory_bytes:kube_proxy"
      labels:
        sysdig: "true"
    - expr: |
        process_cpu_seconds_total{job="kube-proxy"}
      record: "process_cpu_seconds_total:kube_proxy"
      labels:
        sysdig: "true"
    - expr: |
        go_goroutines{job="kube-proxy"}
      record: "go_goroutines:kube_proxy"
      labels:
        sysdig: "true"

  - name: "Sysdig.k8s.etcd.rules"
    rules:
    - expr: up{job=~"etcd"}
      record: "up:kubernetes"
      labels:
        sysdig: "true"
    - expr: |
        process_resident_memory_bytes{job=~"etcd"}
      record: "process_resident_memory_bytes:kubernetes"
      labels:
        sysdig: "true"
    - expr: |
        process_cpu_seconds_total{job=~"etcd"}
      record: "process_cpu_seconds_total:kubernetes"
      labels:
        sysdig: "true"
    - expr: |
        go_goroutines{job=~"etcd"}
      record: "go_goroutines:kubernetes"
      labels:
        sysdig: "true"
    - expr: |
        etcd_server_has_leader
      record: "etcd_server_has_leader:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_server_leader_changes_seen_total
      record: "etcd_server_leader_changes_seen_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        grpc_server_started_total
      record: "grpc_server_started_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        sum by (grpc_type,grpc_code,grpc_service)(grpc_server_handled_total)
      record: "grpc_server_handled_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        grpc_server_handling_seconds_bucket
      record: "grpc_server_handling_seconds_bucket:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_network_peer_round_trip_time_seconds_bucket
      record: "etcd_network_peer_round_trip_time_seconds_bucket:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_debugging_mvcc_db_total_size_in_bytes
      record: "etcd_debugging_mvcc_db_total_size_in_bytes:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_disk_wal_fsync_duration_seconds_bucket
      record: "etcd_disk_wal_fsync_duration_seconds_bucket:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_disk_backend_commit_duration_seconds_bucket
      record: "etcd_disk_backend_commit_duration_seconds_bucket:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_http_failed_total
      record: "etcd_http_failed_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_http_successful_duration_seconds_bucket
      record: "etcd_http_successful_duration_seconds_bucket:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_network_client_grpc_received_bytes_total
      record: "etcd_network_client_grpc_received_bytes_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_network_client_grpc_sent_bytes_total
      record: "etcd_network_client_grpc_sent_bytes_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_network_client_grpc_sent_bytes_total
      record: "etcd_network_client_grpc_sent_bytes_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_server_proposals_failed_total
      record: "etcd_server_proposals_failed_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_server_proposals_committed_total
      record: "etcd_server_proposals_committed_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_server_proposals_applied_total
      record: "etcd_server_proposals_applied_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        etcd_network_peer_sent_failures_total
      record: "etcd_network_peer_sent_failures_total:sysdig"
      labels:
        sysdig: "true"

  - name: "Sysdig.k8s.dns.rules"
    rules:
    - expr: |
        coredns_panic_count_total
      record: "coredns_panic_count_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        coredns_dns_response_rcode_count_total
      record: "coredns_dns_response_rcode_count_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        coredns_forward_response_rcode_count_total
      record: "coredns_forward_response_rcode_count_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        coredns_dns_request_duration_seconds_bucket
      record: "coredns_dns_request_duration_seconds_bucket:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        coredns_dns_request_type_count_total
      record: "coredns_dns_request_type_count_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        coredns_forward_request_count_total
      record: "coredns_forward_request_count_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        coredns_cache_hits_total
      record: "coredns_cache_hits_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        coredns_cache_misses_total
      record: "coredns_cache_misses_total:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        coredns_cache_size
      record: "coredns_cache_size:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        coredns_plugin_enabled
      record: "coredns_plugin_enabled:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        coredns_dns_request_size_bytes_bucket
      record: "coredns_dns_request_size_bytes_bucket:sysdig"
      labels:
        sysdig: "true"
    - expr: |
        coredns_dns_response_size_bytes_bucket
      record: "coredns_dns_response_size_bytes_bucket:sysdig"
      labels:
        sysdig: "true"