apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-agent
  namespace: sysdig-agent
data:
  dragent.yaml: |
    new_k8s: true
    k8s_cluster_name: YourClusterName
    metrics_excess_log: true
    10s_flush_enable: true
    app_checks_enabled: false
    use_promscrape: true
    new_k8s: true
    promscrape_fastproto: true
    prometheus:
      enabled: true
      prom_service_discovery: true
      log_errors: true
      max_metrics: 200000
      max_metrics_per_process: 200000
      max_tags_per_metric: 100
      ingest_raw: true
      ingest_calculated: false
    snaplen: 512
    tags: role:cluster
  prometheus.yaml: |
    global:
      scrape_interval: 10s
    scrape_configs:
    - job_name: php-fpm-default
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_pod_host_ip]
          regex: __HOSTIPS__
        - action: drop
          source_labels: [__meta_kubernetes_pod_annotation_promcat_sysdig_com_omit]
          regex: true
        - action: replace
          source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
          target_label: __scheme__
          regex: (https?)
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          - __meta_kubernetes_pod_annotation_promcat_sysdig_com_integration_type
          regex: (php-fpm-exporter);(.{0}$)
          replacement: php-fpm
          target_label: __meta_kubernetes_pod_annotation_promcat_sysdig_com_integration_type
        - action: keep
          source_labels:
          - __meta_kubernetes_pod_annotation_promcat_sysdig_com_integration_type
          regex: "php-fpm"
        - action: replace
          source_labels: [__meta_kubernetes_pod_uid]
          target_label: sysdig_k8s_pod_uid
        - action: replace
          source_labels: [__meta_kubernetes_pod_container_name]
          target_label: sysdig_k8s_pod_container_name
