apiVersion: v1
kind: Alert
app: Istio
version: 1.0.0
appVersion:
- '1.14'
descriptionFile: ALERTS.md
configurations:
- kind: Prometheus
  data: |-
    groups:
    - name: Istio
      rules:
        - alert: '[Istio-Citadel] CSR without success'
          expr: |
            rate(citadel_server_csr_count[5m]) - rate(citadel_server_success_cert_issuance_count[5m]) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            description: Some of the Certificate Signing Request (CSR) were not correctly requested
        - alert: '[Istio-Pilot] Inbound listener rules conflicts'
          expr: |
            pilot_conflict_inbound_listener > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            description: There are some conflict with inbound listener rules
        - alert: '[Istio-Pilot] Endpoint found in unready state'
          expr: |
            pilot_endpoint_not_ready > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            description: Endpoint found in unready state
        - alert: '[Istio] Unstable requests for sidecar injections'
          expr: |
            rate(sidecar_injection_requests_total[5m]) - rate(sidecar_injection_success_total[5m]) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            description: Sidecar injections requests has no been successfully resolved
        - alert: '[Istio-Envoy] High 4xx RequestError Rate'
          expr: |
            sum (rate(istio_requests_total{ response_code=~"4..", reporter="source"}[5m]))/ sum (rate(istio_requests_total{ reporter="source"}[5m]))> 0.05
          for: 5m
          labels:
            severity: critical
          annotations:
            description: High 4xx RequestError Rate
        - alert: '[Istio-Envoy] High Request Latency'
          expr: |
            histogram_quantile(0.95,sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket[5m])) by (le)) > 100
          for: 5m
          labels:
            severity: critical
          annotations:
            description: Envoy High Request Latency

