apiVersion: v1
kind: Alert
app: ''
version: 1.0.0
appVersion:
- 1.0.0
configurations:
- kind: Prometheus
  data: |
    - alert:
      expr:
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Text {{$labels.label}}
descriptionFile: ALERTS.md
