---
apiVersion: v1
kind: App
name: "Rancher"
keywords: 
  - Platform
  - Coming soon
  - Kubernetes
availableVersions: 
  - '2.5.0'
shortDescription: Run Kubernetes Everywhere
description: |
  # Rancher is open source software that combines everything an organization needs to adopt and run containers in production.
icon: https://raw.githubusercontent.com/sysdiglabs/promcat-resources/master/apps/images/rancher.png
website: https://rancher.com/
available: false
